import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [isDarkMode,setIsDarkMode] = useState(true);
  useEffect(() => {
    if (typeof window !== "undefined") {
      let matched = window.matchMedia('(prefers-color-scheme: dark)').matches;
        if(matched)
          setIsDarkMode(true);
        else
          setIsDarkMode(false);
    }
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Starkpill</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The doctor will see you soon.
        </h1>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          By  
          

            <Image src={isDarkMode ? "/companyLogo.png": "/companyLogoLight.png"} alt="Seraphlabs Logo" width={40} height={40} />
            Seraphlabs
        </a>
      </footer>
    </div>
  )
}
